"""upgrade order_info

Revision ID: 015c23adac58
Revises: 781bf94c93c7
Create Date: 2021-05-31 02:06:37.719543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015c23adac58'
down_revision = '781bf94c93c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'order_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('order_info', 'last_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('order_info', 'city',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_info', 'city',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('order_info', 'last_name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('order_info', 'order_number',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
