"""move remark column to order_info

Revision ID: 5f5976c53b30
Revises: 492d94908192
Create Date: 2021-05-31 17:06:03.890879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5976c53b30'
down_revision = '492d94908192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('remark', sa.String(length=128), nullable=True))
    op.drop_column('order_list', 'remark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_list', sa.Column('remark', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('order_info', 'remark')
    # ### end Alembic commands ###
