"""add auto time

Revision ID: 781bf94c93c7
Revises: ff4a654bfcf0
Create Date: 2021-05-30 13:37:41.373469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781bf94c93c7'
down_revision = 'ff4a654bfcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('update_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'update_on')
    op.drop_column('product', 'created_on')
    # ### end Alembic commands ###
